name = "MyFirstPackage"
uuid = "6f175d77-e7eb-472e-8fd4-132061b5e1ca"
authors = ["Ziao Tang"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
